spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${OAUTH2_GOOGLE_CLIENT_ID}"
            client-secret: "${OAUTH2_GOOGLE_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
          kakao:
            client-id:  "${OAUTH2_KAKAO_CLIENT_ID}"
            client-secret: "${OAUTH2_KAKAO_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
          naver:
            client-id: "${OAUTH2_NAVER_CLIENT_ID}"
            client-secret: "${OAUTH2_NAVER_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              # - nickname
              - profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

easylose:
  frontend-redirect-host: "${FRONTEND_REDIRECT_HOST:${SERVICE_HOST}}"
  frontend-redirect-scheme: "${FRONTEND_REDIRECT_SCHEME:https}"

secret:
  jwt:
    access-secret-string: "${JWT_ACCESS_SECRET_STRING}"
    refresh-secret-string: "${JWT_REFRESH_SECRET_STRING}"
