spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/easylose
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    include: oauth
