spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 419533806012-5v94nfndugtm8bo1e59k79rb19l5njlr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
          kakao:
            client-id:  f22f9b0008a9e034f6a05fb4fdcf1cfb
            client-secret: mxyQNaV4Seo8wp4DcdvkdcYacTb8wMoV
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
          naver:
            client-id: gs_AlLSIVnM0DKNu5nff
            client-secret: 7yOifXTNCf
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              # - nickname
              - profile_image

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

secret:
  jwt:
    access-encode-key: 4IiNArBIPAS9MGWCgrd_oQmuDw2iwkh-idD_5z9g9bSWfb9YSoF47RLDN4yy6csKoM1cm6gdIEW-I5YCiAJwaQ
    refresh-encode-key: M7ltJSUdTmYTrmL8xZFK2CbbktvT1D21ud6XtML-Gvcik4yNTc9mNFJyOGfNFbj4aEGapozuQR1qBM8H1mIzTg
